modLoader="javafml" #mandatory
loaderVersion="[37,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT"

[[mods]] #mandatory
modId="shield" #mandatory
version="1.0" #mandatory
displayName="Shield Mod" #mandatory
logoFile="logo.png" #optional
credits="Omersaban for everything" #optional
authors="Omersaban" #optional
description='''
A fun Mod for magic

'''